name: Compile

on:
  push:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v2

     - name: Remove .github folder from process
       run: |
         rm -r .github
     - name: Deploy ZIP file
       uses: mkyai/zip-deploy@v1.0.7
